version: 2.1

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: cimg/go:1.20  # Use the CircleCI Go image
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout  # Check out the source code

      - setup_remote_docker:
          docker_layer_caching: true  # Set up Docker for building images

      - run:
          name: Build Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t $DOCKERHUB_USERNAME/hello-toby:$TAG .  # Build the Docker image

      - run:
          name: Push application Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/hello-toby:$TAG  # Push the Docker image

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
