version: 2.1

executors:
  docker-executor:
    docker:
      - image: golang:1.20  # Use the official Go image

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout  # Check out the source code

      - setup_remote_docker:
          version: 20.10.7  # Specify the Docker version you want to use
          docker_layer_caching: true  # Optional: Enable layer caching for faster builds

      - run:
          name: Build Docker Image
          command: |
            docker build -t hellotoby .

      - run:
          name: Run Tests (Optional)
          command: |
            go test ./...

      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker tag hellotoby $DOCKER_USERNAME/hellotoby:latest
            docker push $DOCKER_USERNAME/hellotoby:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
